### ISSUE TITLE
Sugestões de Melhorias

### ISSUE THREAD

**Issue by ricardomagamobi** [djonatant/Magazord#1]
- Fazer com que a pasta com que seja acessivel o sistema seja qualquer uma diferente de Magazord. Exemplo: Eu baixei os fontes em uma pasta chamada teste.
Ao acessar http://localhost/teste/public/index.php?rot=Pessoa&aca=101 deu um problema de require dos arquivos

- Fazer com que ao acessar sem os parametros de rotina e acao abra a página padrão. Ex: http://localhost/Magazord/public/index.php

- Os arquivos da pasta de vendor não devem ser comitado no github

- Colocar nas dependencias do composer a plataforma mínima do PHP e também as dependencias de extensões necessárias. Ex: MYSQL

- Fazer um tratamento para ao inserir/alterar uma pessoa com que o CPF seja validado.

- Fornecer instruções de como criar o bando de dados através de comandos no doctrine.
https://www.doctrine-project.org/projects/doctrine-orm/en/2.13/reference/tools.html

- Ao executar o ajax das consultas, caso tenha algum erro o mesmo não está retornando nenhuma mensagem de erro para a interface. Ex: se o banco não esta rodando, ficando somente visivel o erro através do console no navegador.

Bonus:
- Fornecer um arquivo docker-compose para executar o projeto em container. Motivo: Eu não tinha por exemplo nem o mysql nem o php8 instalado em minha máquina, somente o docker.

**Comment by djonatant** [comment]
OBSERVAÇÕES E DIFICULDADES

Tempo de desenvolvimento de todos os itens: 5,5 horas.
Tempo de desenvolvimento dos itens exeto o item bonus: 3.5 horas.

Ambos os tempos divididos em dois períodos.

1. Mesmo definindo a coluna chave da entidade como:
    /**
     * @Id
     * @GenerateValue
     * @Column(type="integer")
     */
     
2. Ao gerar o schema conforme o passo 2 da instalação, o mesmo não gera o AUTO_INCREMENT no banco de dados, portanto acessei o administrador de banco de dados e ajustei manualmente para incrementar valores no id.
Eu não possuia o docker instalado na minha maquina, através de estudos consegui criar um docker-compose, mas não entendi muito bem como testar.

3. O arquivo cli-config.php, quando executado, é o equivalente ao executar 'bin/doctrine orm:schema-tool:create';
